### PR TITLE
Inject environment variables during buildstep

### PR DESCRIPTION
**Pull request by nickveenhof**
This change allows us to use the outputs of a Cloudformation build step in the following build step. It also cleans up the way environment variables are created since dashes are not allowed in an environment variable but if the stackname had a dash it could happen that this became part of the environment variable key. Also I added environment variables without the prefix since stack names can also be generated using environment variables and it becomes really hard to then use those variables as parameters. Without the prefix, that becomes easier WITH the risk that the next stack could overwrite those variables.

### CODE REVIEW

**Comment by nickveenhof** [comment]
Also, this branch includes another pull request to allow environment variables in the cloudformation recipe as I used the same branch to work from. When that one is merged in master, we can reroll this branch

**Comment by nathanagood** [comment]
@nickveenhof Is this one on hold as well until after you have merged into master?

**Comment by phpboyscout** [comment]
Is there any news on this PR being accepted at all?

**Comment by nathanagood** [comment]
@phpboyscout Please see my last question to @nickveenhof, which hasn't been answered.

**Comment by nickveenhof** [comment]
This can be closed, rerolled it and made a new branch and PR, see #31. Should be much cleaner as I didn't try to fix all the markup. That said, there's a ton of markup errors in this plugin that I'll try to address in a new PR as soon as these two ( #31 and #30 ) are merged.

**Comment by prakashriti** [comment]
Hi, Is there any fix for Output variables missing while using AWS CloudFormation as build-step ([https://issues.jenkins-ci.org/browse/JENKINS-26304]). I could still face this issue.  Is there any workaround for this issue ?

**Comment by kadrach** [comment]
A fix for this would be greatly appreciated.

**Pull request closed without merging**
