### PR TITLE
Allow jenkins variables in the cloudformation recipe url or string

### PR DESCRIPTION
**Pull request by nickveenhof**
Currently it is not possible to use the following in the cloudformation recipe:

s3://$VARIABLE/something/something. This patch fixes that and allows flexible builds based on input params.

### CODE REVIEW

**Comment by wsoula** [comment]
This seems like a pretty straight forward change, can it be merged and released?  Would love to be able to give people the ability to pass the recipe as a parameter so I can have a generic cf job people can use to create aws objects.

**Comment by g3p3nk** [comment]
Yes, this is a very good change, please merge this into master.

**Comment by nickveenhof** [comment]
I need to redo this pull request as it comes from my master branch which got other changes merged. Do not merge until further notice. Thanks!

**Comment by nathanagood** [comment]
@nickveenhof do you still want me to hold off on merging? I haven't tried reproducing this yet or testing it.

**Comment by nickveenhof** [comment]
This one can be closed, I did a reroll in a new branch. See #30 for the details. Thanks for the patience.

**Pull request closed without merging**
