### PR TITLE
Added create cloud formation as build & post build step

### PR DESCRIPTION
**Pull request by amitgilad3**
Added option to create cloud formation as 
1.build step
2.post build step

also added sleep timer-how much time to wait after cloud formation is created (incase other steps need to be run).

added prefix option to tear down cloud formation in case you wish to delete older  version of cloud formation that starts with prefix

### CODE REVIEW

**Comment by edovale** [comment]
Hi @amitgilad3 
there seems to be a problem related to outputs not been added as environment variables when spawning a CF as a build step. Would you have a chance to look into this? Please let me know so I can plan accordingly. 
Thanks.

Erick. 

Here is the issue: https://issues.jenkins-ci.org/browse/JENKINS-26304

**Comment by amitgilad3** [comment]
Found problem. 
Fixing it today will update you when i finish

**Comment by edovale** [comment]
Awesome!!! Thanks.

**Comment by mikegchambers** [comment]
Hi, edovale, amitgilad3, 

Great plugin, thanks!

Fantastic to hear that there is a fix on the way for the missing outputs. Any news on its progress? 

Any chance of a sneak preview? I'm ready to test! 

Cheers - Mike

**Comment by mikegchambers** [comment]
OK, for anyone playing along at home the fix (along with some other changes) is here:
https://github.com/nicolas-nannoni/jenkins-cloudformation-plugin

Which I have compiled here:
http://s3.aws.mikegchambers.com/jenkins-cloudformation-plugin.hpi

Note:
- Outputs are placed in a file within the Workspace: 'aws_stack_output.properties' (not EnvVar).
- The region parameter has been made a text input to allow you to pass an EnvVar (not tested).

**Comment by baxterj** [comment]
Hello, is there any chance of an official release with this fix soon? Thanks.

**Comment by prakashriti** [comment]
Hi, Is there any fix for **Output variables missing while using AWS CloudFormation as build-step** ([https://issues.jenkins-ci.org/browse/JENKINS-26304]). I could still face this issue. Ans also i could not see any files like 'aws_stack_output.properties' in the workspace as mentioned by @mikegchambers . Is there any workaround for this issue ?

**Comment by cptguy** [comment]
Hi, @mikegchambers @amitgilad3 , I still don't see the outputs anywhere when creating a cloudformation stack as a build-step. Is there going to be an official release for this at all?

**Comment by Burden50** [comment]
@cptguy I just took over maintenance of this plugin I'm just working my way though the backlog of pulls I hope to itemize them into a list of objectives and merge them.

**Pull request merged**
